### ISSUE TITLE
Caps Lock Light Not Working

### ISSUE THREAD

**Issue by ashvinnihalani** [afzalarsalan/linux-surfacebook#11]
This seems like a problem that dissapers and reappers based on the kernel so ill create this issue to keep track of it. Currently 4.18.3-arch1-1-surfacebook not working

**Comment by ashvinnihalani** [comment]
New Kernel Up: 4.18.4-arch1-1-surfacebook
Update: Light Still Not Working
On Deepin DE, CAPS Lock triggers the animation

**Comment by afzalarsalan** [comment]
Can confirm, triaging atm

**Comment by afzalarsalan** [comment]
This issue looks to be fixed as of kernel version 4.18.10. @ashvinnihalani please confirm if this issue still exists so I can close this issue

**Comment by afzalarsalan** [comment]
This is fixed in two versions of kernel updates so it's not a fluke. Let me know if this still isn't working for you
