### ISSUE TITLE
IPTS Guide / GPU - Reached Target Graphical

### ISSUE THREAD

**Issue by itsyoshio** [afzalarsalan/linux-surfacebook#4]
[ OK ] Started Flush Journal to Persistent Storage.
[drm:csr_load_work_fn [i915]] *ERROR* Firmware has wrong CSS header length 1097158924 bytes
[drm:intel_guc_setup [i915]] *ERROR* GuC init failed: -5
[drm:i915_gem_init [i915]] *ERROR*Failed to initialize GPU, declaring it wedged
ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0A: open gpu error : -5
ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0A: error in handling resp msg
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:63 / ret_size:0
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:63 / ret_size:0
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:63
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:7
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:12
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:0
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:4
i2c_hid i2c-MSHW0030:00: error in i2c_hid_init_report size:19 / ret_size:15
[ OK ] Found device /dev/disk/by.uuid/16B5-8F9A.

I'm back at Reached Target Graphical Interface, but i cannot log in to Shell or anything because my TTY keeps flashing.
(The Boot Log keeps flashing over my TTY every second, and for that time i cannot type)

This happens for both Master (4.9) and linux-410(4.10r5) branch.

I followed the IPTS Guide for every part except the "CONFIG_INTEL_IPTS=m" Kernel Config, because that's obviously handled in your Code.

( 
-retrieved GuC and DMW Firmware, created Symbolic Links for that,
-got all 5 IPTS .bin files and Symbolic Linked those.
 )

I will try inspecting further to the best of my abilities and respond on News.

**Comment by alkeryn** [comment]
if you can acess a terminal try removing all files in /lib/firmware/i915 then
reinstall the linux-firmware package, that might fix it

**Comment by afzalarsalan** [comment]
Well 4.10 branch is pretty broken right now so don't use that. I think this
might be caused by you overwriting the GuC and DMW firmware as I'm pretty
sure the firmware on that wiki page is older than the one present in the
linux-firmware package on Arch Linux. You're going to want to delete any
changes you made a reinstall the linux-firmware package. I really should
clear this up in my own wiki post but I'm a little busy at the moment.

**Comment by itsyoshio** [comment]
ok, reinstalling linux-firmware fixed the problem.
I can no use my Keyboard and Multitouch.

But the touchscreen ain't working. I followed the Instructions for the file linking again (except the guc and dmw of course)

Weirdly, i just noticed that the Pen is working as a Mouse in my Gnome. Not in Google Chrome but outside of it the pointer works.

**Comment by afzalarsalan** [comment]
Your touchscreen isn't working but your pen is working? That's the first I've heard of that combination; Also try the different versions of the files because one of them gave me inverted touch for whatever reason. Also the Chrome thing is because XWayland doesn't support touch events yet or basically anything other than mouse.

**Comment by itsyoshio** [comment]
Yes, my Pen is functioning as a Second Mouse 
(and in fact, will also give me a second cursor on the desktop that can be moved independent of my touchpads cursor)

with this second cursor i don't seem to be able to left click (or right click). So i can't interact with most Stuff, i can however close a window by tapping my pen on the close icon.

very weird.
I will try the other files and report back.

**Comment by itsyoshio** [comment]
0076.bin works for me (except Left and Right Click with Pen, I'll probably just have to bind the pen as a mouse hid)

0078.bin enables pen cursor but touch doesn't work
0079.bin does not work at all.

European Surface Book, i5 Model with DGPU and German QWERTZ Layout.
