### ISSUE TITLE
Touchpad gesture not working on 4.10 (master)

### ISSUE THREAD

**Issue by alkeryn** [afzalarsalan/linux-surfacebook#6]
I know that touchscreen don't work yet but the same goes for the touchpad gestures (2finger scroll ect...)
also i had to install the 4.10 kernel because when using the one of the 49 branch, i have extremely low wifi (don't go over around 25 / 30 kB /s while on windows or 4.10 i have around 4 MB /s)

I'm on surface pro 4 i5 4GB
Removed the synaptic driver for reverse scrolling on gnome

**Comment by afzalarsalan** [comment]
Yes I need to patch in Touch convert support as it seems they only added Surface Book support natively. Should have that in by tonight

**Comment by alkeryn** [comment]
Have you an idea for the slow wifi issue ? it's around 30kB/s (download) while on windows my network is about 4 MB /s (so more than 100 x faster ^^")

**Comment by afzalarsalan** [comment]
I mean it could be the wifi patch but I hit 10 MB down on my University network with it all the time so that doesn't make much sense. Might be some weird powersave configuration if you don't use TLP etc. See if there's anything fishy in dmesg

**Comment by alkeryn** [comment]
I removed powertop and TLP to test it out but it didn't changed anything
Here is my dmesg 
[dmesg.txt](https://github.com/afzalarsalan/linux-surfacebook/files/818940/dmesg.txt)

**Comment by Alkeryn** [comment]
Powertop*

**Comment by alkeryn** [comment]
Actually it dosen't work better on 4.10
I realised that it randomly work, sometime it is limited to 30kB/s and then randomly it is back to normal (4mB/s)

Whenever i disconect and reconect it is fast again for like 3 second then slow again and sometime after it is fast again but the time before it is random seem to be random and it also seem that it don't always happen so i don't know what can cause the wifi to be slow at "random" moment
The thing is, it is slow most of the time and fast moment are really rare 
I know it isn't a wifi issue since my others computer & device work fine
while on the surface sometime i can't even load a small webpage

**Comment by afzalarsalan** [comment]
I have fixed the touchpad issue as of the latest commit in master. As for the wifi issue, it may be specific to your network so you may want to try another network and see if the issue is reoccurring.

**Comment by alkeryn** [comment]
I tryied on my hotspot (phone ) network
My mother's house network 
and my home network
Always the same issue
On dmesg, mwifiex_pcie give some errors and "incompatible network configuration" but i don't know if it is linked 
here is a dmesg | grep wifi :
[mwifi.txt](https://github.com/afzalarsalan/linux-surfacebook/files/819370/mwifi.txt)
but thank for all your work i'm now compilling the kernel
can i support your work in any way ?

**Comment by alkeryn** [comment]
So i installed, touchpad gesture work again on type cover so i think this issue can be closed
still waiting for touchscreen and pen before using this kernel though ^^
