### ISSUE TITLE
Applying patch to 4.13 breaks multitouch

### ISSUE THREAD

**Issue by bjmnbraun** [afzalarsalan/linux-surfacebook#8]
On my surfacebook, branch 4.9 runs fine and has multitouch gestures on the touchscreen. As an exercise, I applied the most recent patch to a fresh checkout of Linux kernel 4.13.9 from source and everything works great, except that multitouch seems to fail (when using more than one finger, xev shows nothing.)

**Comment by afzalarsalan** [comment]
Yeah it's currently something I'm trying to get squared away on my free time. Something in 4.10+ broke the code path and trying to get multi touch back is definitely going to take some debugging.

**Comment by afzalarsalan** [comment]
Fixed in 4.14, make sure you put the ipts firmware where it belongs. It's in the master branch
